apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-03-26T20:34:56Z"
  labels:
    app: frontend
  name: frontend
  namespace: default
  resourceVersion: "30496"
  uid: f7c687df-e69c-4c53-a4ba-d7bbff1ef6e1
spec:
  clusterIP: 10.43.231.98
  clusterIPs:
  - 10.43.231.98
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
